apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  labels:
    appname: mongodb
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: ocs-storagecluster-ceph-rbd-encrypted
  resources:
    requests:
      storage: 40Gi
