resources:
- busybox-dc-1.yaml
- busybox-pvc-1.yaml
- busybox-dc-2.yaml
- busybox-pvc-2.yaml
- busybox-dc-3.yaml
- busybox-pvc-3.yaml
- busybox-dc-4.yaml
- busybox-pvc-4.yaml
- busybox-dc-5.yaml
- busybox-pvc-5.yaml
- busybox-dc-6.yaml
- busybox-pvc-6.yaml
- busybox-dc-7.yaml
- busybox-pvc-7.yaml
- busybox-dc-8.yaml
- busybox-pvc-8.yaml
- busybox-dc-9.yaml
- busybox-pvc-9.yaml
- busybox-dc-10.yaml
- busybox-pvc-10.yaml
- pvc_11.yaml
- pvc_12.yaml
- pvc_13.yaml
- pvc_14.yaml
- pvc_15.yaml
- pvc_16.yaml
- pvc_17.yaml
- pvc_18.yaml
- pvc_19.yaml
- pvc_20.yaml
- pvc_21.yaml
- pvc_22.yaml
- pvc_23.yaml
- pvc_24.yaml
- pvc_25.yaml
- pvc_26.yaml
- pvc_27.yaml
- pvc_28.yaml
- pvc_29.yaml
- pvc_30.yaml
- pvc_31.yaml
- pvc_32.yaml
- pvc_33.yaml
- pvc_34.yaml
- pvc_35.yaml
- pvc_36.yaml
- pvc_37.yaml
- pvc_38.yaml
- pvc_39.yaml
- pvc_40.yaml
- pvc_41.yaml
- pvc_42.yaml
- pvc_43.yaml
- pvc_44.yaml
- pvc_45.yaml
- pvc_46.yaml
- pvc_47.yaml
- pvc_48.yaml
- pvc_49.yaml
- pvc_50.yaml
- pvc_51.yaml
- pvc_52.yaml
- pvc_53.yaml
- pvc_54.yaml
- pvc_55.yaml
- pvc_56.yaml
- pvc_57.yaml
- pvc_58.yaml
- pvc_59.yaml
- pvc_60.yaml
- pvc_61.yaml
- pvc_62.yaml
- pvc_63.yaml
- pvc_64.yaml
- pvc_65.yaml
- pvc_66.yaml
- pvc_67.yaml
- pvc_68.yaml
- pvc_69.yaml
- pvc_70.yaml
- pvc_71.yaml
- pvc_72.yaml
- pvc_73.yaml
- pvc_74.yaml
- pvc_75.yaml
- pvc_76.yaml
- pvc_77.yaml
- pvc_78.yaml
- pvc_79.yaml
- pvc_80.yaml
- pvc_81.yaml
- pvc_82.yaml
- pvc_83.yaml
- pvc_84.yaml
- pvc_85.yaml
- pvc_86.yaml
- pvc_87.yaml
- pvc_88.yaml
- pvc_89.yaml
- pvc_90.yaml
- pvc_91.yaml
- pvc_92.yaml
- pvc_93.yaml
- pvc_94.yaml
- pvc_95.yaml
- pvc_96.yaml
- pvc_97.yaml
- pvc_98.yaml
- pvc_99.yaml
- pvc_100.yaml
