apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app1
    workloadpattern: simple_io_pvc
  name: busybox-pvc-46
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 46Gi
  storageClassName: ocs-storagecluster-ceph-rbd
