---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: pv_encryption
    apps.open-cluster-management.io/github-path: rdr/busybox/cephfs/app-busybox-2/resources
  labels:
    app: busybox-sample-cephfs-2
  name: busybox-sub
spec:
    channel: ramen-busybox-cephfs-2/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: busybox-placement
