---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: pv_encryption
    apps.open-cluster-management.io/github-path: rdr/mysql/app-mysql-2/resources
  labels:
    app: mysql-sample
  name: mysql-sub
spec:
    channel: ramen-mysql-2/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: mysql-placement
