---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: pv_encryption
    apps.open-cluster-management.io/github-path: rdr/busybox/app-busybox-2/resources
  labels:
    app: multi-busybox-sample
  name: multi-busybox-sub-2
spec:
    channel: ramen-busybox-multisnap-1/ramen-gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: multi-sub-busybox-placement-2
